-- MySQL Script generated by MySQL Workbench
-- 12/04/15 07:23:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lojurta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lojurta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lojurta` DEFAULT CHARACTER SET utf8 ;
USE `lojurta` ;

-- -----------------------------------------------------
-- Table `lojurta`.`Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojurta`.`Loja` (
  `idLoja` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `CNPJ` VARCHAR(14) NOT NULL,
  `site` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `foto` LONGTEXT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`idLoja`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojurta`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojurta`.`Categoria` (
  `idCategoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojurta`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojurta`.`Produto` (
  `idProduto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `valor` FLOAT UNSIGNED NOT NULL,
  `estoque` INT UNSIGNED NOT NULL,
  `descricao` LONGTEXT NULL,
  `foto` LONGTEXT NULL,
  `data` DATETIME NOT NULL,
  `Loja_idLoja` INT UNSIGNED NOT NULL,
  `Categoria_idCategoria` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_Produto_Loja1_idx` (`Loja_idLoja` ASC),
  INDEX `fk_Produto_Categoria1_idx` (`Categoria_idCategoria` ASC),
  CONSTRAINT `fk_Produto_Loja1`
    FOREIGN KEY (`Loja_idLoja`)
    REFERENCES `lojurta`.`Loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `lojurta`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojurta`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojurta`.`Cliente` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `CPF` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojurta`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojurta`.`Endereco` (
  `idEndereco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(100) NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `ativo` TINYINT(1) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `UF` CHAR(2) NOT NULL,
  `Cliente_idCliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Endereço_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Endereço_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `lojurta`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojurta`.`Promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojurta`.`Promocao` (
  `idPromocao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `desconto` INT NOT NULL,
  `dataIni` DATETIME NOT NULL,
  `dataFim` DATETIME NOT NULL,
  `Produto_idProduto` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPromocao`),
  INDEX `fk_Promoção_Produto1_idx` (`Produto_idProduto` ASC),
  CONSTRAINT `fk_Promoção_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `lojurta`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojurta`.`Carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojurta`.`Carrinho` (
  `idCarrinho` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Cliente_idCliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCarrinho`),
  INDEX `fk_Carrinho_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Carrinho_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `lojurta`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojurta`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojurta`.`Venda` (
  `idVenda` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataCompra` DATETIME NOT NULL,
  `valorTotal` FLOAT NULL,
  `formaPagamento` VARCHAR(45) NULL,
  `Cliente_idCliente` INT UNSIGNED NOT NULL,
  `Endereço_idEndereco` INT UNSIGNED NOT NULL,
  `Carrinho_idCarrinho` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_Venda_Cliente1_idx` (`Cliente_idCliente` ASC),
  INDEX `fk_Venda_Endereço1_idx` (`Endereço_idEndereco` ASC),
  INDEX `fk_Venda_Carrinho1_idx` (`Carrinho_idCarrinho` ASC),
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `lojurta`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Endereço1`
    FOREIGN KEY (`Endereço_idEndereco`)
    REFERENCES `lojurta`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Carrinho1`
    FOREIGN KEY (`Carrinho_idCarrinho`)
    REFERENCES `lojurta`.`Carrinho` (`idCarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lojurta`.`ProdutoNoCarrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lojurta`.`ProdutoNoCarrinho` (
  `Produto_idProduto` INT UNSIGNED NOT NULL,
  `Carrinho_idCarrinho` INT UNSIGNED NOT NULL,
  `quantidade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Carrinho_idCarrinho`),
  INDEX `fk_Produto_has_Carrinho_Carrinho1_idx` (`Carrinho_idCarrinho` ASC),
  INDEX `fk_Produto_has_Carrinho_Produto1_idx` (`Produto_idProduto` ASC),
  CONSTRAINT `fk_Produto_has_Carrinho_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `lojurta`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Carrinho_Carrinho1`
    FOREIGN KEY (`Carrinho_idCarrinho`)
    REFERENCES `lojurta`.`Carrinho` (`idCarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
